"""
SKU21284 Dual Channel Relay Library for Raspberry Pi Pico
MicroPython library for controlling the Pico Dual Channel Relay Hat
https://learn.sb-components.co.uk/Pico-Dual-Channel-Relay-Hat

Author: Generated by AI Assistant
Version: 1.0
"""

from machine import Pin
import time

class SKU21284:
    """
    Control class for SKU21284 Dual Channel Relay Hat
    
    The relay uses active-low logic (LOW = ON, HIGH = OFF)
    Default GPIO pins based on the product documentation:
    - Relay 1: GP21
    - Relay 2: GP20
    """
    
    def __init__(self, relay1_pin=21, relay2_pin=20, active_low=False):
        """
        Initialize the dual channel relay
        
        Args:
            relay1_pin (int): GPIO pin for relay 1 (default: 21)
            relay2_pin (int): GPIO pin for relay 2 (default: 20)
            active_low (bool): Whether the relay uses active-low logic (default: True)
        """
        self.active_low = active_low
        
        # Initialize relay pins
        self.relay1 = Pin(relay1_pin, Pin.OUT)
        self.relay2 = Pin(relay2_pin, Pin.OUT)
        
        # Turn off both relays initially
        self.off(1)
        self.off(2)
        
        print(f"Dual Channel Relay initialized - Relay1: GP{relay1_pin}, Relay2: GP{relay2_pin}")
    
    def _get_relay_state(self, state):
        """Convert desired state to actual pin state based on active_low logic"""
        if self.active_low:
            return 0 if state else 1
        else:
            return 1 if state else 0
    
    def on(self, channel):
        """
        Turn ON the specified relay channel
        
        Args:
            channel (int): Relay channel (1 or 2)
        """
        pin_state = self._get_relay_state(True)
        
        if channel == 1:
            self.relay1.value(pin_state)
        elif channel == 2:
            self.relay2.value(pin_state)
        else:
            raise ValueError("Channel must be 1 or 2")
    
    def off(self, channel):
        """
        Turn OFF the specified relay channel
        
        Args:
            channel (int): Relay channel (1 or 2)
        """
        pin_state = self._get_relay_state(False)
        
        if channel == 1:
            self.relay1.value(pin_state)
        elif channel == 2:
            self.relay2.value(pin_state)
        else:
            raise ValueError("Channel must be 1 or 2")
    
    def toggle(self, channel):
        """
        Toggle the state of the specified relay channel
        
        Args:
            channel (int): Relay channel (1 or 2)
        """
        if channel == 1:
            current_state = self.relay1.value()
            self.relay1.value(not current_state)
        elif channel == 2:
            current_state = self.relay2.value()
            self.relay2.value(not current_state)
        else:
            raise ValueError("Channel must be 1 or 2")
    
    def state(self, channel):
        """
        Get the current state of the specified relay channel
        
        Args:
            channel (int): Relay channel (1 or 2)
            
        Returns:
            bool: True if relay is ON, False if OFF
        """
        if channel == 1:
            pin_state = self.relay1.value()
        elif channel == 2:
            pin_state = self.relay2.value()
        else:
            raise ValueError("Channel must be 1 or 2")
        
        if self.active_low:
            return pin_state == 0
        else:
            return pin_state == 1
    
    def all_on(self):
        """Turn ON both relays"""
        pin_state = self._get_relay_state(True)
        self.relay1.value(pin_state)
        self.relay2.value(pin_state)
    
    def all_off(self):
        """Turn OFF both relays"""
        pin_state = self._get_relay_state(False)
        self.relay1.value(pin_state)
        self.relay2.value(pin_state)
    
    def all_toggle(self):
        """Toggle both relays"""
        self.toggle(1)
        self.toggle(2)
    
    def pulse(self, channel, duration_ms=1000):
        """
        Send a pulse to the specified relay (ON for duration, then OFF)
        
        Args:
            channel (int): Relay channel (1 or 2)
            duration_ms (int): Pulse duration in milliseconds
        """
        self.on(channel)
        time.sleep_ms(duration_ms)
        self.off(channel)
    
    def sequence(self, channels, delay_ms=500):
        """
        Activate relays in sequence
        
        Args:
            channels (list): List of channel numbers to activate in sequence
            delay_ms (int): Delay between activations in milliseconds
        """
        for channel in channels:
            if channel not in [1, 2]:
                raise ValueError("Channel must be 1 or 2")
            self.on(channel)
            time.sleep_ms(delay_ms)
            self.off(channel)

    # Example usage and test function
    def test_relay(self):
        """Test function to demonstrate the relay library"""
        
        # Initialize the relay
        
        print("Testing Dual Channel Relay...")
        
        # Test individual channels
        print("Turning on Relay 1 for 2 seconds...")
        self.on(1)
        time.sleep(2)
        self.off(1)

        print("Turning on Relay 2 for 2 seconds...")
        self.on(2)
        time.sleep(2)
        self.off(2)

        # Test toggle
        print("Toggling both relays...")
        self.toggle(1)
        self.toggle(2)
        time.sleep(1)
        self.toggle(1)
        self.toggle(2)

        # Test pulse
        print("Pulsing Relay 1 for 1 second...")
        self.pulse(1, 1000)

        # Test sequence
        print("Running sequence: 1 -> 2 -> both")
        self.sequence([1, 2], 1000)
        time.sleep(0.5)
        self.all_on()
        time.sleep(1)
        self.all_off()

        print("Test completed!")

